# Imports

In [14]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [15]:
#base
import pandas as pd
import numpy as np
from scipy import stats
# visual
import matplotlib.pyplot as plt
import seaborn as sns
#path
from pathlib import Path
import sys

In [22]:
#Config
PROJECT_ROOT = Path().resolve().parent
sys.path.insert(0, str(PROJECT_ROOT))
from src.config import load_config
cfg = load_config(PROJECT_ROOT / "configs" / "config.yaml")

#settings
RANDOM_STATE = cfg.data.random_state

#data_paths
TARGET_PATH = cfg.paths.raw_target_path(PROJECT_ROOT)
USERS_PATH = cfg.paths.raw_users_path(PROJECT_ROOT)

#src
sys.path.append(str(PROJECT_ROOT / cfg.paths.src_dir))

In [23]:
#src
from eda import full_eda_report, analyze_numeric, plot_distributions, plot_correlation_matrix, analyze_categorical, detect_outliers
from visual import setup_plotting

In [26]:
#Matplotlib_Settings
%matplotlib inline
setup_plotting()

# Data Loading

In [25]:
assert USERS_PATH.exists(), f'File not founded: {USERS_PATH}'
df = pd.read_csv(USERS_PATH)
df.head()

C:\Users\Максим\AppData\Local\Temp\ipykernel_3768\3232408817.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(USERS_PATH)

,session_id,client_id,visit_date,visit_time,visit_number,utm_source,utm_medium,utm_campaign,utm_adcontent,utm_keyword,device_category,device_os,device_brand,device_model,device_screen_resolution,device_browser,geo_country,geo_city
0,9055434745589932991.1637753792.1637753792,2108382700.163776,2021-11-24,14:36:32,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,NaN,360x720,Chrome,Russia,Zlatoust
1,905544597018549464.1636867290.1636867290,210838531.163687,2021-11-14,08:21:30,1,MvfHsxITijuriZxsqZqt,cpm,FTjNLDyTrXaWYgZymFkV,xhoenQgDQsgfEPYNPwKO,IGUCNvHlhfHpROGclCit,mobile,Android,Samsung,NaN,385x854,Samsung Internet,Russia,Moscow
2,9055446045651783499.1640648526.1640648526,2108385331.164065,2021-12-28,02:42:06,1,ZpYIoDJMcFzVoPFsHGJL,banner,LEoPHuyFvzoNfnzGgfcd,vCIpmpaGBnIQhyYNkXqp,puhZPIYqKXeFPaUviSjo,mobile,Android,Huawei,NaN,360x720,Chrome,Russia,Krasnoyarsk
3,9055447046360770272.1622255328.1622255328,2108385564.162225,2021-05-29,05:00:00,1,kjsLglQLzykiRbcDiGcD,cpc,NaN,NOBKLgtuvqYWkXQHeYWM,NaN,mobile,NaN,Xiaomi,NaN,393x786,Chrome,Russia,Moscow
4,9055447046360770272.1622255345.1622255345,2108385564.162225,2021-05-29,05:00:00,2,kjsLglQLzykiRbcDiGcD,cpc,NaN,NaN,NaN,mobile,NaN,Xiaomi,NaN,393x786,Chrome,Russia,Moscow

In [27]:
assert TARGET_PATH.exists(), f'File not founded: {TARGET_PATH}'
targets = pd.read_csv(TARGET_PATH)
targets.head()

,session_id,hit_date,hit_time,hit_number,hit_type,hit_referer,hit_page_path,event_category,event_action,event_label,event_value
0,5639623078712724064.1640254056.1640254056,2021-12-23,597864.0,30,event,NaN,sberauto.com/cars?utm_source_initial=google&ut...,quiz,quiz_show,NaN,NaN
1,7750352294969115059.1640271109.1640271109,2021-12-23,597331.0,41,event,NaN,sberauto.com/cars/fiat?city=1&city=18&rental_c...,quiz,quiz_show,NaN,NaN
2,885342191847998240.1640235807.1640235807,2021-12-23,796252.0,49,event,NaN,sberauto.com/cars/all/volkswagen/polo/e994838f...,quiz,quiz_show,NaN,NaN
3,142526202120934167.1640211014.1640211014,2021-12-23,934292.0,46,event,NaN,sberauto.com/cars?utm_source_initial=yandex&ut...,quiz,quiz_show,NaN,NaN
4,3450086108837475701.1640265078.1640265078,2021-12-23,768741.0,79,event,NaN,sberauto.com/cars/all/mercedes-benz/cla-klasse...,quiz,quiz_show,NaN,NaN

# DF EDA

In [28]:
num_cols, cat_cols = full_eda_report(df)

============================================================
DATASET OVERVIEW
============================================================
Shape: 1,860,042 rows x 18 columns
Memory: 1691.21 MB
Duplicates: 0 (0.00%)

--- DATA TYPES ---
  object: 17 columns
  int64: 1 columns

--- MISSING VALUES ---
                 Count  Percent
device_model   1843704    99.12
utm_keyword    1082061    58.17
device_os      1070138    57.53
device_brand    367178    19.74
utm_adcontent   335615    18.04
utm_campaign    219603    11.81
utm_source          97     0.01

--- NUMERIC COLUMNS ---
  1 columns: ['visit_number']

--- CATEGORICAL COLUMNS ---
  17 columns: ['session_id', 'client_id', 'visit_date', 'visit_time', 'utm_source', 'utm_medium', 'utm_campaign', 'utm_adcontent', 'utm_keyword', 'device_category', 'device_os', 'device_brand', 'device_model', 'device_screen_resolution', 'device_browser', 'geo_country', 'geo_city']

In [33]:
analyze_categorical(df)

==================================================
Column: session_id | Unique: 1860042 | Missing: 0
  Too many categories (1860042), showing top 10:
session_id
9055434745589932991.1637753792.1637753792    1
905544597018549464.1636867290.1636867290     1
9055446045651783499.1640648526.1640648526    1
9055447046360770272.1622255328.1622255328    1
9055447046360770272.1622255345.1622255345    1
9055447192389856083.1622453074.1622453074    1
9055455318486370642.1640843788.1640843788    1
9055461992850812764.1626107740.1626107740    1
9055462349345527315.1638536723.1638536723    1
9055466554104774132.1624800757.1624800757    1

==================================================
Column: client_id | Unique: 1391717 | Missing: 0
  Too many categories (1391717), showing top 10:
client_id
1750498477.162945    462
130918396.162801     334
1266574870.162314    309
736859557.161956     306
1894772482.162186    276
1065181919.163161    271
1136708344.163342    257
1761941933.162184    254
260799907.1631       252
943676978.162189     248

==================================================
Column: visit_date | Unique: 226 | Missing: 0
  Too many categories (226), showing top 10:
visit_date
2021-05-24    39453
2021-12-21    30704
2021-05-25    19305
2021-06-29    17367
2021-09-14    16204
2021-12-31    15910
2021-10-29    15818
2021-11-16    15253
2021-06-28    15169
2021-11-15    15009

==================================================
Column: visit_time | Unique: 85318 | Missing: 0
  Too many categories (85318), showing top 10:
visit_time
12:00:00    61067
13:00:00    61002
10:00:00    60211
14:00:00    60178
11:00:00    59887
16:00:00    58854
15:00:00    57684
18:00:00    56575
19:00:00    55699
20:00:00    55520

==================================================
Column: utm_source | Unique: 293 | Missing: 97
  Too many categories (293), showing top 10:
utm_source
ZpYIoDJMcFzVoPFsHGJL    578290
fDLlAcSmythWSCVMvqvL    300575
kjsLglQLzykiRbcDiGcD    266354
MvfHsxITijuriZxsqZqt    186199
BHcvLfOaCWvWTykYqHVe    116320
bByPQxmDaMXgpHeypKSM    102287
QxAxdyPLuQMEcrdZWdWb     51415
aXQzDWsJuGXeBXexNHjc     31152
jaSOmLICuBzCFqHfBdRg     29241
RmEBuqrriAfAVsLQQmhk     28055

==================================================
Column: utm_medium | Unique: 56 | Missing: 0
  Too many categories (56), showing top 10:
utm_medium
banner      552272
cpc         434794
(none)      300575
cpm         242083
referral    152050
organic      63034
email        29240
push         28035
stories      10582
cpv           8022

==================================================
Column: utm_campaign | Unique: 412 | Missing: 219603
  Too many categories (412), showing top 10:
utm_campaign
LTuZkdKfxRGVceoWkVyg    463481
LEoPHuyFvzoNfnzGgfcd    324044
FTjNLDyTrXaWYgZymFkV    247360
gecBYcKZCPMcVYdSSzKP    134042
TmThBvoCcwkCZZUWACYq     26597
XHNUiSKKGTEpSAlaVMFQ     24524
okTXSMadDkjvntEHzIjp     24511
SgIUDYUKnyWHVowUOqid     22841
sbJRYgVfvcnqKJNDDYIr     20188
LwJZxKuWmvOhPsaCeRjG     17615

==================================================
Column: utm_adcontent | Unique: 286 | Missing: 335615
  Too many categories (286), showing top 10:
utm_adcontent
JNHcPlZPxEMWDnRiyoBf    1006599
vCIpmpaGBnIQhyYNkXqp     181048
xhoenQgDQsgfEPYNPwKO     113072
PkybGvWbaqORmxjNunqZ      60316
LLfCasrxQzJIyuldcuWy      24222
TuyPWsGQruPMpKvRxeBF      18189
UxrnyMlRBSOhOjytXnMG      13583
dUuXlWzvmhDSyclWRhNP      10280
yYdBRbPmBMUZHXwqGxNx       9700
WYLajZgbUhGimwBKDZUH       8610

==================================================
Column: utm_keyword | Unique: 1219 | Missing: 1082061
  Too many categories (1219), showing top 10:
utm_keyword
puhZPIYqKXeFPaUviSjo    506819
aXQzDWsJuGXeBXexNHjc     24241
pHqgLcdBQPSLcrTpLkdr     13767
ITfrGJNwVsHBGJMAKoct     13353
hAmNSZmQkKQKAjZEGlgb     11297
UKNBOHebRIIsQRsjNKay     10946
IGUCNvHlhfHpROGclCit      7568
RkpOyeEPgcMBSDuHLQcj      6978
JajANoFxoqXfKRNBUhzx      6758
BmOOOIoWGHEfxEfoUezs      6602

==================================================
Column: device_category | Unique: 3 | Missing: 0
device_category
mobile     79.3
desktop    19.7
tablet      1.0

==================================================
Column: device_os | Unique: 13 | Missing: 1070138
device_os
Android          58.7
iOS              26.2
Windows          11.2
Macintosh         3.1
Linux             0.6
(not set)         0.0
Chrome OS         0.0
BlackBerry        0.0
Tizen             0.0
Samsung           0.0
Windows Phone     0.0
Firefox OS        0.0
Nokia             0.0

==================================================
Column: device_brand | Unique: 205 | Missing: 367178
  Too many categories (205), showing top 10:
device_brand
Apple        551088
Samsung      332194
Xiaomi       288367
Huawei       185853
Realme        19058
(not set)     17545
OPPO          13504
Vivo          11740
OnePlus        9965
Asus           7929

==================================================
Column: device_model | Unique: 104 | Missing: 1843704
  Too many categories (104), showing top 10:
device_model
AuMdmADEIoPXiWpTsBEj    9778
tWBQlsvNfHxRUjaPAfhd     653
cwMJxNXiWUgMUxGiCTPs     651
pTgAEPipQxDXCjPrJbHo     461
FJApgTrMAGHoxCxQVKws     372
tfPZFRbtlzEssBEesRwM     335
pcvPxfVFaAmhwFmvIeYd     325
aCLaTVQlHcXbUnQYQvIg     236
mzJXHtJPIOSHoHtgezIA     235
JAIKWwxRffFOXQcfGTVi     198

==================================================
Column: device_screen_resolution | Unique: 5039 | Missing: 0
  Too many categories (5039), showing top 10:
device_screen_resolution
414x896      169090
1920x1080    125768
375x812      117944
393x851      115454
375x667       93341
360x780       92182
360x800       80547
412x915       74744
360x640       70588
390x844       60827

==================================================
Column: device_browser | Unique: 57 | Missing: 0
  Too many categories (57), showing top 10:
device_browser
Chrome              1013436
Safari               478562
YaBrowser            133311
Safari (in-app)       69912
Android Webview       55369
Samsung Internet      47309
Opera                 26817
Firefox               16588
Edge                  16065
UC Browser              871

==================================================
Column: geo_country | Unique: 166 | Missing: 0
  Too many categories (166), showing top 10:
geo_country
Russia           1800565
United States      11784
Ukraine             9012
Ireland             4034
Belarus             3636
Sweden              2694
Kazakhstan          2279
Germany             2232
Turkey              1953
Netherlands         1549

==================================================
Column: geo_city | Unique: 2548 | Missing: 0
  Too many categories (2548), showing top 10:
geo_city
Moscow              805329
Saint Petersburg    296788
(not set)            78172
Yekaterinburg        35788
Krasnodar            32243
Kazan                29531
Samara               24992
Nizhny Novgorod      22227
Ufa                  21679
Novosibirsk          21568

#ВЫВОДЫ:

## Типы данных:
Все фичи являются типо object, однако имеются такие колонки как visit_date, visit_time которые могут/должны быть преобразованы в date, time соответственно. Device screen resolution можно распарсить в ширину и высоту а также площадь что бы 

## Missing Valuse:
- Device_model: 99.12% пропусков + закодирована => удаляем фичу
- utm_keyword: ключевое слово 58.17% + закодирована => восстановить невозможно, но есть доминирующее ключевое слово, можно сделать фичу является ли ключевое слово доминантным или нет(пропуски = нет)
- device_os: 57.53% пропусков, есть 2 варианта заполнения т.к. есть 3 доминирующих операционных системы можно заполнить с сохранением пропорции, но более чистый вариант будет либо удалить, либо заполнить (not set)
- device_brand: 19,74% пропусков, нет ярко выраженного доминантного производителя, заполню (not set)
- utm_adcontent: 18.04% пропусков + закодирована, есть доминантный представитель, можно заполнить им, либо ввести новую категорию (not set) + 286 уникальных категорий из которых большую половину занимает 1 категорию, можно добавить фичу принадлежит ли данной фиче
- utm_campaign: 11.81% + закодирована: нет доминирующей категории => либо распределить в соответствии с пропорциями первых 4 т.к. они в сумме дают высокий процент по фиче либо удалить эти объекты
- utm_source: 0.01% + закодирована: либо удалить объекты либо попробовать восстановить из других закодированных фич где совпадения такие же как и в пропусках(например utm_medium + utm_campaign)

## Наличие доминантных категорий
- utm_adcontent
- utm_keyword
- device_os(android+ iOS+ Windows)
-